CognizantQLESS.Site/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CognizantQLESS.Core.Models;
using CognizantQLESS.DAL;
using CognizantQLESS.Core.Constants;
using Microsoft.AspNetCore.Authorization;

namespace CognizantQLESS.Site.Controllers
{
    [Authorize(Roles = Constants.ROLE_ADMIN)]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("Admin/")]
        [Route("Admin/TransportCards")]
        [Route("Admin/Index")]
        public async Task<IActionResult> TransportCards()
        {
            return View(await _context.TransportCards.ToListAsync());
        }
        
        public async Task<IActionResult> TransportCardDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transportCard = await _context.TransportCards
                .FirstOrDefaultAsync(m => m.TransportCardId == id);
            if (transportCard == null)
            {
                return NotFound();
            }

            return View(transportCard);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TransportCardCreate()
        {
            var transportCard = new TransportCard();
            transportCard.Load = 100;
            transportCard.PurchaseDate = DateTime.Now;

            if (ModelState.IsValid)
            {
                _context.Add(transportCard);
                await _context.SaveChangesAsync();

                // transfer to trigger
                transportCard.SerialNumber = transportCard.GenerateSerialNumber();
                await _context.SaveChangesAsync();

                return RedirectToAction("TransportCards");
            }
            return RedirectToAction("TransportCards");
        }

        public async Task<IActionResult> TransportCardDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transportCard = await _context.TransportCards
                .FirstOrDefaultAsync(m => m.TransportCardId == id);
            if (transportCard == null)
            {
                return NotFound();
            }

            return View(transportCard);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TransportCardDeleteConfirmed(int id)
        {
            var transportCard = await _context.TransportCards.FindAsync(id);
            _context.TransportCards.Remove(transportCard);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransportCardExists(int id)
        {
            return _context.TransportCards.Any(e => e.TransportCardId == id);
        }
    }
}

CognizantQLESS.Site/Controllers/PassengerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CognizantQLESS.Core.Models;
using CognizantQLESS.DAL;
using CognizantQLESS.Core.Constants;
using CognizantQLESS.Core.Models.ViewModels;
using Newtonsoft.Json;
using Microsoft.Extensions.Caching.Memory;
using CognizantQLESS.Site.Services;
using CognizantQLESS.Core.Interface;

namespace CognizantQLESS.Site.Controllers
{
    public class PassengerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMemoryCache _memoryCache;
        private readonly CacheSeeder _cacheSeeder;
        private readonly IFareCalculator _fareCalculator;

        private List<StationLineViewModel> stationLines;
        private List<StationViewModel> stations;
        private List<FareCacheViewModel> fares;

        public PassengerController(ApplicationDbContext context, IMemoryCache memoryCache, CacheSeeder cacheSeeder, IFareCalculator fareCalculator)
        {
            _context = context;
            _memoryCache = memoryCache;
            _cacheSeeder = cacheSeeder;
            _fareCalculator = fareCalculator;
        }

        public ActionResult DiscountRegistration()
        {
            if (TempData[Constants.UI_MESSAGE] != null)
            {
                ViewData[Constants.UI_MESSAGE] = JsonConvert.DeserializeObject<UIMessageViewModel>((string)TempData[Constants.UI_MESSAGE]);
            }
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DiscountRegistration([Bind("SerialNumber,SeniorCitizenControlNumber,PWDIdNumber")] DiscountRegistrationViewModel discountRegistrationModel)
        {
            if (!discountRegistrationModel.IsValid)
            {
                ModelState.AddModelError("PWDIdNumber", Constants.ERR_DISCOUNTREGISTRATION_MISSING);
                ModelState.AddModelError("SeniorCitizenControlNumber", Constants.ERR_DISCOUNTREGISTRATION_MISSING);
            }

            if (ModelState.IsValid)
            {
                var transportCard = await _context.TransportCards.FirstOrDefaultAsync(t => t.SerialNumber == discountRegistrationModel.SerialNumber);

                if (transportCard == null)
                {
                    ModelState.AddModelError("SerialNumber", Constants.ERR_INCORRECT_SERIALNUMBER);
                    return View(discountRegistrationModel);
                }
                else if (!transportCard.CanBeRegisteredAsDiscount)
                {
                    TempData[Constants.UI_MESSAGE] = JsonConvert.SerializeObject(new UIMessageViewModel()
                    {
                        IsSuccess = false,
                        Message = String.Format(Constants.ERR_ALREADY_REGISTERED_OR_PAST_REGISTRATION, transportCard.DiscountRegistrationDate?.ToString("MM/dd/yyyy") ?? "Empty")
                    });

                    return RedirectToAction("DiscountRegistration");
                }
                else if (!transportCard.IsValid)
                {
                    TempData[Constants.UI_MESSAGE] = JsonConvert.SerializeObject(new UIMessageViewModel()
                    {
                        IsSuccess = false,
                        Message = String.Format(Constants.ERR_CARD_EXPIRED, transportCard.ExpirationDate)
                    });
                    return RedirectToAction("DiscountRegistration");
                }

                transportCard.PWDIdNumber = discountRegistrationModel.PWDIdNumber;
                transportCard.SeniorCitizenControlNumber = discountRegistrationModel.SeniorCitizenControlNumber;
                transportCard.DiscountRegistrationDate = DateTime.Now;
                transportCard.LastUsedDate = DateTime.Now;

                try
                {
                    _context.Update(transportCard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransportCardExists(transportCard.TransportCardId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (Exception e)
                {
                    TempData[Constants.UI_MESSAGE] = JsonConvert.SerializeObject(new UIMessageViewModel()
                    {
                        IsSuccess = false,
                        Message = String.Format(Constants.ERR_GENERIC, e.Message)
                    });
                    return RedirectToAction("TopUp");
                }

                TempData[Constants.UI_MESSAGE] = JsonConvert.SerializeObject(new UIMessageViewModel()
                {
                    IsSuccess = true,
                    Message = Constants.SUCCESS_DISCOUNTREGISTRATION
                });

                return RedirectToAction("DiscountRegistration");
            }
            return View(discountRegistrationModel);
        }

        public ActionResult TopUp()
        {
            if (TempData[Constants.UI_MESSAGE] != null)
            {
                ViewData[Constants.UI_MESSAGE] = JsonConvert.DeserializeObject<UIMessageViewModel>((string)TempData[Constants.UI_MESSAGE]);
            }
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TopUp([Bind("SerialNumber,Amount,Cash")] LoadViewModel loadViewModel)
        {
            if (ModelState.IsValid)
            {
                TransportCard transportCard = await _context.TransportCards.FirstOrDefaultAsync(t => t.SerialNumber == loadViewModel.SerialNumber);

                if (!loadViewModel.IsCashAmountValid)
                {
                    ModelState.AddModelError("Cash", Constants.ERR_INSUFFICIENT_CASH);
                    return View(loadViewModel);
                }
                else if (transportCard == null)
                {
                    ModelState.AddModelError("SerialNumber", Constants.ERR_INCORRECT_SERIALNUMBER);
                    return View(loadViewModel);
                }
                else if (!transportCard.IsValid)
                {
                    TempData[Constants.UI_MESSAGE] = JsonConvert.SerializeObject(new UIMessageViewModel()
                    {
                        IsSuccess = false,
                        Message = String.Format(Constants.ERR_CARD_EXPIRED, transportCard.ExpirationDate)
                    });
                    return RedirectToAction("TopUp");
                }

                LoadHistory newHistory = new LoadHistory(loadViewModel, transportCard);
                transportCard.Load += loadViewModel.Amount;
                transportCard.LastUsedDate = DateTime.Now;

                try
                {
                    _context.LoadHistories.Add(newHistory);
                    _context.Update(transportCard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransportCardExists(transportCard.TransportCardId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (Exception e)
                {
                    TempData[Constants.UI_MESSAGE] = JsonConvert.SerializeObject(new UIMessageViewModel()
                    {
                        IsSuccess = false,
                        Message = String.Format(Constants.ERR_GENERIC, e.Message)
                    });
                    return RedirectToAction("TopUp");
                }

                TempData[Constants.UI_MESSAGE] = JsonConvert.SerializeObject(new UIMessageViewModel() {
                    IsSuccess = true,
                    Message = String.Format(Constants.SUCCESS_TOPUP, loadViewModel.Change, newHistory.RunningBalance)
                });

                return RedirectToAction("TopUp");
            }

            return View(loadViewModel);
        }

        public ActionResult Travel()
        {
            if (TempData[Constants.UI_MESSAGE] != null)
            {
                ViewData[Constants.UI_MESSAGE] = JsonConvert.DeserializeObject<UIMessageViewModel>((string)TempData[Constants.UI_MESSAGE]);
            }

            GetDropdowns();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Travel([Bind("SerialNumber,OriginStationId,DestinationStationId")] TravelViewModel travelViewModel)
        {
            if (travelViewModel.OriginStationId == travelViewModel.DestinationStationId)
            {
                ModelState.AddModelError("OriginStationId", Constants.ERR_SAME_ORIGINDESTINATION);
                ModelState.AddModelError("DestinationStationId", Constants.ERR_SAME_ORIGINDESTINATION);
            }

            if (ModelState.IsValid)
            {
                GetFares();

                var fareModel = fares.FirstOrDefault(
                    f => f.OriginStationId == travelViewModel.OriginStationId &&
                    f.DestinationStationId == travelViewModel.DestinationStationId);

                if (fareModel == null)
                {
                    TempData[Constants.UI_MESSAGE] = JsonConvert.SerializeObject(new UIMessageViewModel()
                    {
                        IsSuccess = false,
                        Message = String.Format(Constants.ERR_FAREMODEL_MISSING, travelViewModel.OriginStationId, travelViewModel.DestinationStationId)
                    });

CognizantQLESS.Site/Views/Shared/_Layout.cshtml
@using CognizantQLESS.Core.Constants

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CognizantQLESS.Site</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;700;900&family=Nunito:wght@300&display=swap" rel="stylesheet">
    <style>
        html * {
            font-family: 'Nunito', sans-serif !important;
            font-family: 'Nunito Sans', sans-serif !important;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CQLESS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">---</span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(Constants.ROLE_ADMIN)) {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="TransportCards">Transport Cards</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Passenger" asp-action="TopUp">Top Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Passenger" asp-action="DiscountRegistration">Discount Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Passenger" asp-action="Travel">Travel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @{
                if (ViewData[Constants.UI_MESSAGE] != null)
                {
                    await Html.RenderPartialAsync("_UIMessagePartial", ViewData[Constants.UI_MESSAGE]);
                }
            }

            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="float-left">&copy; 2022 - CognizantQLESS</div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CognizantQLESS.Site/Views/Shared/_UIMessagePartial.cshtml
@model CognizantQLESS.Core.Models.ViewModels.UIMessageViewModel

@{       
    string alertType = (Model.IsSuccess) ? "alert-success" : "alert-danger";
}

<div class="row">
    <div class="col-12">
        <div class="alert @alertType">
            @Model.Message
        </div>
    </div>
    <br />
</div> 